import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULTS} from '../src/core.js';
const ownId='11111111-1111-4111-8111-111111111111',kolId='22222222-2222-4222-8222-222222222222';
const event=()=>({addListener(fn){this.fn=fn;}});const area=()=>({data:{},async get(k){return k===null?structuredClone(this.data):{[k]:structuredClone(this.data[k])};},async set(p){Object.assign(this.data,structuredClone(p));},async remove(k){delete this.data[k];},async setAccessLevel(){}});
const local=area(),session=area();
globalThis.chrome={storage:{local,session},runtime:{id:'test',getURL:p=>'chrome-extension://test/'+p,onMessage:event(),onInstalled:event(),onStartup:event()},action:{onClicked:event()},alarms:{onAlarm:event(),async clear(){},async create(){}}};
await import('../src/background.js');
const msg=(type,extra={})=>new Promise(resolve=>chrome.runtime.onMessage.fn({type,...extra},{id:'test',url:'chrome-extension://test/src/options.html'},resolve));
const trade=(id,q,buy=10,sell=0)=>({id,tokenAddress:'0xabc',networkId:56,humanTokenAmount:q,sumSwapOpen:buy,sumSwapClosed:sell,sumTransferIn:0,sumTransferOut:0,closedAt:q===0?'2026-09-06T03:00:00Z':null,createdAt:'2026-09-06T01:00:00Z',updatedAt:'2026-09-06T03:00:00Z',avgEntryPrice:1});
let mode, kolTrade,following,total,holders,requests,tgFail,tgCount,cap,tgBodies;
const own=()=>({balance:{tokenAddress:'0xabc',shiftedBalance:10},tokenFilterResult:{marketCap:cap,priceUSD:'2',token:{networkId:56,symbol:'TEST'}},activeTrade:trade('own-trade',10),valuation:{includeUnrealizedPnl:true}});
function setup(){cap=100;mode='ok';kolTrade=trade('kol-trade',10);following=[kolId];total=1;holders=true;requests=[];tgFail=false;tgCount=0;tgBodies=[];local.data={config:{...DEFAULTS,enabled:true,myProfile:'demo_user'}};session.data={auth:{authorization:'Bearer testonlytoken',owner:{id:ownId,handle:'demo_user'}}};}
globalThis.fetch=async(url,opt)=>{requests.push(String(url));let path=new URL(url).pathname,body;
 if(new URL(url).hostname==='api.telegram.org'){tgCount++;tgBodies.push(JSON.parse(opt.body));return {ok:!tgFail,status:tgFail?500:200,async json(){return {ok:!tgFail};}};}
 if(mode==='auth')return {ok:false,status:431,headers:new Headers(),async json(){return {error:'unauthorized'};}};
 if(path.endsWith('/userHandle/demo_user'))body={id:ownId,userHandle:'demo_user'};
 else if(path.endsWith('/balances')){if(mode==='network')throw new Error('offline');body=mode==='malformed'?{balances:[{}]}:{balances:[own()]};}
 else if(path.endsWith('/followingIds'))body={followingIds:following};
 else if(path==='/hodlers/top')body=[{tokenAddress:'0xabc',networkId:56,totalHolders:1,topHolders:[{user:{id:kolId,userHandle:'KOL'},tradeId:'kol-trade',humanAmount:10,value:20,averageEntryPrice:1,unrealizedPnl:10,costBasis:10}]}];
 else if(path==='/hodlers/friends')body={tokens:[{tokenAddress:'0xabc',networkId:56,totalHolders:total,topHolders:holders?[{user:{id:kolId,userHandle:'KOL'},tradeId:'kol-trade'}]:[]}]};
 else if(path==='/trades/kol-trade')body={userId:kolId,trade:kolTrade};
 else if(path==='/feed/token')body={items:[],hasNextPage:false};else throw new Error('unexpected '+path);
 return {ok:true,status:200,headers:new Headers(),async json(){return {success:true,responseObject:body};}};
};
test('worker baseline, add, HOLD and validated exit',async()=>{setup();await msg('POLL');assert.equal(local.data.state.events.length,0);kolTrade=trade('kol-trade',15,15);await msg('POLL');assert.deepEqual(local.data.state.events.map(e=>e.type),['ADD']);await msg('POLL');assert.equal(local.data.state.events.length,1);holders=false;total=0;kolTrade=trade('kol-trade',0,15,15);await msg('POLL');assert.equal(local.data.state.events.at(-1).type,'EXIT');assert(requests.every(u=>u.startsWith('https://prod-api.fomo.family/')));});
test('malformed and failed balances preserve snapshots',async()=>{setup();await msg('POLL');const original=structuredClone(local.data.state.own);mode='network';await msg('POLL');assert.deepEqual(local.data.state.own,original);mode='malformed';await msg('POLL');assert.deepEqual(local.data.state.own,original);assert.equal(local.data.state.events.length,0);});
test('unfollow is not sell',async()=>{setup();await msg('POLL');following=[];await msg('POLL');assert.equal(local.data.state.events.length,0);assert.deepEqual(local.data.state.tokens['0xabc:56'].holders,{});});
test('truncation cannot generate exit from missing holder',async()=>{setup();await msg('POLL');holders=false;total=51;await msg('POLL');assert.equal(local.data.state.events.length,0);assert.equal(local.data.state.tokens['0xabc:56'].holders[kolId].state,'UNKNOWN');});
test('invalid auth is explicit and old data retained',async()=>{setup();await msg('POLL');const original=structuredClone(local.data.state.own);mode='auth';await msg('POLL');assert.match(local.data.state.status,/会话/);assert.deepEqual(local.data.state.own,original);});
test('Telegram failed send remains queued and secrets are hidden',async()=>{setup();local.data.config={...local.data.config,telegramEnabled:true,telegramBotToken:'123:secretvalue',telegramChatId:'123'};await msg('POLL');tgFail=true;kolTrade=trade('kol-trade',20,20);await msg('POLL');assert.equal(local.data.state.outbox.length,1);assert.equal(tgCount,1);const view=await msg('GET');assert.equal(view.config.telegramBotToken,'[saved]');assert(!JSON.stringify(view.state.logs).includes('secretvalue'));tgFail=false;local.data.state.outbox[0].nextAt=0;await msg('POLL');assert.equal(local.data.state.outbox.length,0);assert.equal(tgCount,2);});
test('wrong signed-in profile fails before holdings access',async()=>{setup();session.data.auth.owner.id=kolId;await msg('POLL');assert.match(local.data.state.status,/不一致/);assert.equal(requests.length,1);});
test('profile cache removes redundant lookup and optional activity is off',async()=>{setup();await msg('POLL');await msg('POLL');assert.equal(requests.filter(u=>u.includes('/userHandle/')).length,1);assert.equal(requests.filter(u=>u.includes('/feed/token')).length,0);});
test('floating window reuses existing window and recovers after close',async()=>{setup();let created=0,focused=0,exists=true;chrome.windows={async create(){created++;return {id:7};},async update(id){assert.equal(id,7);if(!exists)throw Error('closed');focused++;}};assert.equal((await msg('FLOAT')).ok,true);await msg('FLOAT');assert.equal(created,1);assert.equal(focused,1);exists=false;await msg('FLOAT');assert.equal(created,2);});

test('market rule creates Telegram event independent of trade alert switches',async()=>{setup();local.data.config={...local.data.config,telegramEnabled:true,telegramBotToken:'123:secretvalue',telegramChatId:'123',alertPositionChanges:false};await msg('POLL');assert.equal((await msg('SAVE_RULE',{key:'0xabc:56',rule:{enabled:true,base:100,multiples:'2,3'}})).ok,true);cap=350;await msg('POLL');assert.equal(local.data.state.events.filter(e=>e.type==='MARKET_CAP').length,2);assert.equal(tgCount,2);await msg('POLL');assert.equal(tgCount,2);});

test('token mute purges pending alerts and blocks subsequent KOL sends',async()=>{setup();Object.assign(local.data.config,{telegramEnabled:true,telegramBotToken:'123:secretvalue',telegramChatId:'123'});await msg('POLL');tgFail=true;kolTrade=trade('kol-trade',20,20);await msg('POLL');assert.equal(local.data.state.outbox.length,1);assert.equal((await msg('TOKEN_ALERTS',{key:'0xabc:56',enabled:false})).ok,true);assert.equal(local.data.state.outbox.length,0);tgFail=false;kolTrade=trade('kol-trade',30,30);await msg('POLL');assert.equal(tgCount,1);});
test('bulk selection overrides legacy disabled rule and bulk off blocks all',async()=>{setup();local.data.config.marketRules={'0xabc:56':{enabled:false}};await msg('TOKEN_ALERTS',{all:false,key:'0xabc:56',enabled:true});await msg('TOKEN_ALERTS',{all:true,enabled:false});assert.equal(local.data.config.tokenAlertsDefault,false);assert.deepEqual(local.data.config.tokenAlerts,{});await msg('TOKEN_ALERTS',{all:true,enabled:true});assert.equal(local.data.config.tokenAlertsDefault,true);});
test('new installations require an explicit profile',async()=>{setup();local.data.config.myProfile='';await msg('POLL');assert.equal(requests.length,0);assert.match(local.data.state.status,/FOMO 名称/);});
test('floating window centers within current browser window',async()=>{setup();let options;chrome.windows={async getLastFocused(){return {left:100,top:50,width:1200,height:900};},async create(o){options=o;return {id:19};}};await msg('FLOAT');assert.equal(options.left,440);assert.equal(options.top,110);});
test('tier rule save and upward cap notification remain supported',async()=>{setup();await msg('POLL');const result=await msg('SAVE_RULE',{key:'0xabc:56',rule:{enabled:true,base:100,tiers:[{direction:'up',mode:'percent',value:100},{direction:'down',mode:'percent',value:20}]}});assert.equal(result.ok,true);cap=220;await msg('POLL');assert.equal(local.data.state.events.filter(e=>e.type==='MARKET_CAP').length,1);});

test('toolbar click opens a resizable monitor and retains saved dimensions',async()=>{setup();local.data.windowSize={width:700,height:900};let options;chrome.windows={async getLastFocused(){return {left:0,top:0,width:1200,height:1000};},async create(o){options=o;return {id:33};}};await chrome.action.onClicked.fn();assert.equal(options.type,'popup');assert.equal(options.width,700);assert.equal(options.height,900);assert.equal(options.left,250);assert.equal(options.top,50);});

test('Telegram delivery includes bold entity without interpreting user HTML',async()=>{setup();Object.assign(local.data.config,{telegramEnabled:true,telegramBotToken:'123:secretvalue',telegramChatId:'123'});await msg('POLL');kolTrade=trade('kol-trade',20,20);await msg('POLL');assert.equal(tgBodies[0].entities[0].type,'bold');assert.match(tgBodies[0].text,/🟩 加仓/);assert.equal(tgBodies[0].parse_mode,undefined);});
test('GET reports Chrome alarm deadline for countdown',async()=>{setup();chrome.alarms.get=async()=>({scheduledTime:123456});const r=await msg('GET');assert.equal(r.schedule.nextAt,123456);assert.equal(r.schedule.inProgress,false);delete chrome.alarms.get;});
