// Local UI translations only. Account names, addresses, input values and logs are never translated.
export const dictionary={
'已暂停':'Paused','待同步':'Sync needed','检查中':'Checking','待调度':'Unscheduled','等待执行':'Pending','无持仓':'No positions','限流 ':'Rate limit ','下一轮计划检查时间；KOL 为下一批，非全部完成':'Next scheduled check; KOL means the next batch, not completion of all tokens','设置与调试':'Settings','设置':'Settings','切换语言':'Switch language','支持作者':'Support the developer','♥ 支持作者':'♥ Support the developer','复制地址':'Copy address','✅ 已复制':'✅ Copied','已复制':'Copied','请选中地址复制':'Please select and copy the address','关闭':'Close',
'如果这个工具对你有帮助，欢迎自愿支持后续维护与改进。':'If this tool helps you, you can optionally support its maintenance and development.',
'支持完全自愿，不影响任何功能。转账前请核对网络与地址。':'Support is optional and does not unlock features. Check the network and address before transferring.',
'持仓观察':'Portfolio monitor','自动监控开启':'Monitoring on','自动监控暂停':'Monitoring paused','后台监控已开启':'Monitoring on','后台监控已暂停':'Monitoring paused','已更新 · API 后台轮询':'Updated · background API polling','未同步登录会话':'No synced session','尚未同步':'Not synced','加载中…':'Loading…','处理中…':'Working…','已完成':'Done',
'当前非现金持仓总价值':'Total position value (excludes cash)','当前持仓总价值':'Total position value','部分持仓估值缺失 · 未包含现金余额':'Some valuations missing · cash excluded','我的持仓更新：':'Positions updated: ','立即检查 API':'Refresh data','持仓金额':'Position value','未实现盈亏':'Unrealized P&L','盈亏待确认':'P&L unavailable','平均建仓市值（估算）':'Average entry market cap (est.)','等待更新':'Waiting for an update','关注者列表不完整':'Following list is incomplete','数据较旧，请检查刷新状态':'Data is stale; check refresh status','当前没有非现金持仓。':'No non-cash positions.','先到设置页输入 FOMO 名称并同步持仓。':'Enter your FOMO handle in Settings and sync your positions.',
'盈亏为平均买入价口径的未实现估算；不含已实现盈亏。':'P&L is an unrealized estimate based on average entry price; realized P&L is excluded.',
'前10大持仓':'Top 10 holders','最低买入市值10人':'Lowest entry · 10','我关注的KOL':'Following','排行加载中，等待下一轮更新。':'Rankings pending; waiting for the next update.','关注者详情暂不可用。':'Following details unavailable.','持仓排行暂不可用。':'Holder rankings unavailable.','当前筛选没有有效记录。':'No valid records for this filter.','仅对接口已返回的持仓者样本排序，非全体最低买入排名。':'Sorted within the returned holder sample, not the lowest entries across all holders.',
'排序依据为估算建仓市值；缺失买入价的记录不参与。':'Sorted by estimated entry market cap; rows without an entry price are excluded.',
'接口返回的持仓排行，不代表链上全部钱包。':'FOMO holder ranking; does not represent all on-chain wallets.',
'匹配成交样本金额，可能不完整':'Matched sample amount; may be incomplete','操作记录':'Activity','暂无已记录操作':'No recorded activity','仅显示本插件已记录的变化，不代表完整历史。':'Changes recorded by this extension only, not a full history.','AI 分析（即将推出）':'AI analysis (coming soon)','投资逻辑 AI 分析将在后续版本开放。':'Investment thesis AI analysis will be available in a future version.',
'持有':'Holding','加仓':'Added','减仓':'Reduced','清仓':'Exited','买入':'Bought','卖出':'Sold','待确认':'Unavailable','我的盈亏':'My P&L','关注者':'Following','待发送':'Queued','关注':'Following','持仓':'Positions','市值':'Market cap',
'首次读取建立基线。价格涨跌不会触发加仓或减仓；不完整数据标为待确认。':'The first check establishes a baseline. Price changes do not count as buys or sells; incomplete data is marked unavailable.',
'拖动窗口边缘调整大小':'Drag the window edges to resize','打开浮窗':'Open monitor','刷新显示':'Refresh view','后台直接读取 API · 无页面扫描或自动打开标签页':'Background API data · no page scanning or automatic tabs',
'1 · 同步 FOMO 会话':'1 · Sync your FOMO session','安装后，手动刷新已登录的 ':'After installation, refresh your signed-in ', '，等待页面完成加载，再点「刷新显示」。同步后可以关闭 FOMO 标签页。':', wait for it to finish, then refresh this view. You can close FOMO after syncing.',
'仅观察官网请求中的登录令牌和当前用户 ID，不扫描仓位或页面。令牌只保存到浏览器会话内存；浏览器重启或令牌过期后需再次手动刷新。不会自动登录或续期。':'Only observes session credentials and the current user ID from existing FOMO requests. Credentials remain in session storage. Refresh FOMO after a browser restart or expiry; no automatic login or renewal.',
'尚无会话，请手动刷新已登录的 FOMO 页面':'No session. Refresh your signed-in FOMO page.','清除当前会话':'Clear session','手动令牌备用方式':'Manual token fallback','仅在自动同步失败时使用。必须确认此令牌属于下方填写的 Profile；此方式无法独立验证令牌所有者。不要粘贴钱包私钥或助记词。':'Use only if automatic sync fails. Confirm this token belongs to your configured profile; this mode cannot independently verify its owner. Never enter wallet keys or seed phrases.',
'我确认这是我的监控 Profile 当前登录令牌':'I confirm this is the current session token for my monitored profile','验证并临时保存':'Validate and save for this session','请先确认令牌属于当前 Profile':'Confirm that the token belongs to the current profile first',
'2 · 监控设置':'2 · Monitoring','开启后台定时监控':'Enable background monitoring','我的 FOMO 用户名':'My FOMO handle','输入你的FOMO名称':'Enter your FOMO handle','刷新方案':'Refresh preset','均衡 · 市值每分钟，KOL 每 5 分钟':'Balanced · positions 1 min / KOL 5 min','更及时 · 市值每 30 秒，KOL 每 2 分钟':'Faster · positions 30 sec / KOL 2 min','省资源 · 市值每 3 分钟，KOL 每 15 分钟':'Economy · positions 3 min / KOL 15 min','自定义':'Custom','高级性能设置':'Advanced performance','市值与我的持仓（分钟）':'Positions interval (minutes)','KOL 最短复查间隔（分钟）':'KOL minimum interval (minutes)','每轮最多检查 Token 数':'Max tokens per check',
'每次市值检查覆盖全部当前持仓；KOL 分批轮询。网络繁忙时延后，不堆积检查任务。Chrome 退出或电脑休眠时暂停。':'Each position check covers all current tokens; KOL checks are batched. Network delays do not create overlapping jobs. Checks pause when Chrome exits or the computer sleeps.',
'我的持仓 BUY / ADD / SELL / EXIT 告警':'My position change alerts','关注者 BUY / ADD / SELL / EXIT 告警':'Following position change alerts','开启 Telegram 告警':'Enable Telegram alerts','Bot Token（留空保留已保存值）':'Bot Token (leave blank to keep saved token)','删除已保存的 Bot Token':'Remove saved Bot Token','先在 Telegram 中向自己的机器人发送 /start。Bot Token 保存于本机 Chrome 扩展存储，不会写入调试导出。测试按钮会发送一条消息。':'Send /start to your bot first. The token is stored locally and excluded from debug exports. Testing sends a message.','保存后测试 Telegram':'Save and test Telegram','保存设置':'Save settings','已保存；留空保留':'Saved; leave blank to keep',
'每个 Token 的市值提醒':'Per-token market cap alerts','默认基准按平均买入价换算建仓市值（估算），可输入 K / M / B。上涨和下跌独立设置，支持涨跌幅、倍数或目标市值。':'The default baseline estimates entry market cap from average entry price. K / M / B input is supported. Set upward and downward targets separately as percentages, multiples or market caps.',
'保存时建立基线，之后按设定方向越线提醒。每档一次，可重新布防；这些规则只发通知，不执行卖出。':'Saving establishes a baseline. Each directional crossing alerts once; rearm to reset. These rules notify only and never place trades.',
'一键全选告警':'Enable all token alerts','全部取消告警':'Disable all token alerts','全部告警（勾选自动保存）':'All alerts (saved automatically)','启用市值阈值规则（需保存）':'Enable market cap rules (save required)','基准建仓市值（美元 · 估算）':'Entry market cap baseline (USD · estimated)','例如 750K、1.2M':'e.g. 750K, 1.2M','平均买入价 × 当前隐含供应量':'Average entry price × current implied supply','使用持仓买入市值':'Use estimated entry market cap','缺少有效买入价时需手动设置，不以当前市值代替。':'Enter a baseline manually if the entry price is missing; current market cap is not used as a substitute.',
'📈 上涨提醒':'📈 Upward alerts','📉 下跌提醒':'📉 Downward alerts','上涨幅度 %':'Increase %','下跌幅度 %':'Decrease %','基准倍数 ×':'Baseline multiple ×','目标市值 USD':'Target market cap USD','上涨阈值':'Upward threshold','下跌阈值':'Downward threshold','＋ 增加上涨档位':'+ Add upward level','＋ 增加下跌档位':'+ Add downward level','删除':'Delete','预览目标':'Preview targets','保存该 Token':'Save token rules','重新布防':'Rearm','已保存 · 等待后续越线':'Saved · waiting for a future crossing','规则仅发送 Telegram 提醒，不自动买卖。每档每方向一次。':'Rules only send Telegram alerts, never trades. Each level alerts once per direction.',
'调试日志':'Debug logs','包含接口路径、状态码、耗时和异常。不包含令牌、Cookie 或完整响应。导出仍含用户名与持仓信息。':'Includes request paths, status codes, timing and errors, but no credentials, cookies or full responses. Exports still contain usernames and positions.','导出调试 JSON':'Export debug JSON','重建监控基线':'Reset baseline','重建基线会清空本插件快照、变化记录和待发送队列；下一次不发送历史变化。继续？':'Reset snapshots, recorded changes and queued alerts? The next check will establish a fresh baseline.',
'此版本基于 2026-09-06 官网实际请求。非官方 API 可能变化；列表与成交记录均来自 FOMO，不能保证覆盖平台外交易。详见项目 README 和接口说明。':'Based on FOMO requests captured on September 6, 2026. Unofficial APIs may change; FOMO data may omit external trades. See the README and API notes.',
'网络请求失败':'Network request failed','会话缺失或失效：请手动刷新已登录的 FOMO 页面':'Session missing or expired: refresh your signed-in FOMO page','接口限流，等待重试':'Rate limited; waiting to retry','请先在设置中输入你的 FOMO 名称':'Enter your FOMO handle in Settings first','已同步':'Synced','上涨至 ':'Cross above ','下跌至 ':'Cross below ','基准 ':'Baseline ', '会话：':'Session: ',' · 所有者由手动确认':' · owner manually confirmed',' 人 · ':' people · ', '更新时间：':'Updated: '
};
let language='zh';export const getLanguage=()=>language;
const ordered=Object.entries(dictionary).sort((a,b)=>b[0].length-a[0].length);
export function translate(text,lang=language){if(lang!=='en')return text;if(dictionary[text])return dictionary[text];
 const cadence=text.match(/^全部 (.+) 个持仓：市值约每 (.+)检查；KOL 一次完整复查保守估算约 (.+) 分钟（网络耗时另计）。$/);if(cadence)return `All ${cadence[1]} positions every ${cadence[2].replace(' 秒',' sec').replace(' 分钟',' min')}; full KOL cycle about ${cadence[3]} min plus network time.`;
 // Replace only known UI fragments; longest-first avoids partially translating headings.
 return text.replace(new RegExp(ordered.map(([s])=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g'),match=>dictionary[match]);
}
const originals=new WeakMap();let observer;let pending=false;
function transform(node,key,value,set){const states=originals.get(node)??{};const state=states[key];const source=state&&state.output===value?state.source:value;const output=translate(source);states[key]={source,output};originals.set(node,states);if(output!==value)set(output);}
export function applyLanguage(){if(!document.body)return;observer?.disconnect();document.documentElement.lang=language==='en'?'en':'zh-CN';document.title='FOMO Monitor'+(location.pathname.endsWith('options.html')?(language==='en'?' · Settings':' · 设置'):'');
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){if(node.parentElement?.closest('script,style,input,textarea,.notranslate,#logs'))continue;const n=node;transform(n,'text',n.nodeValue,v=>n.nodeValue=v);}
 for(const e of document.querySelectorAll('[title],[placeholder],[aria-label]')){if(e.closest('.notranslate'))continue;for(const key of ['title','placeholder','aria-label'])if(e.hasAttribute(key))transform(e,key,e.getAttribute(key),v=>e.setAttribute(key,v));}
 const button=document.getElementById('language');if(button){button.textContent=language==='zh'?'EN':'中';button.title=language==='zh'?'Switch to English':'切换为中文';button.setAttribute('aria-label',button.title);}
 observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','placeholder','aria-label']});
}
export async function initLanguage(){const saved=await chrome.storage.local.get('language');language=saved.language==='en'?'en':'zh';const button=document.createElement('button');button.id='language';button.className='icon-button notranslate';document.querySelector('header').append(button);button.onclick=async()=>{language=language==='zh'?'en':'zh';await chrome.storage.local.set({language});applyLanguage();};
 observer=new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;applyLanguage();});});applyLanguage();chrome.storage.onChanged.addListener((change,area)=>{if(area==='local'&&change.language){language=change.language.newValue==='en'?'en':'zh';applyLanguage();}});
}
