import {translate} from './i18n.js';
import {parseCompact,normalizeRule} from './market-rules.js';
import {tokenAlertsEnabled} from './core.js';
import {$,send,el,time,tokenCards,action,compact,support} from './ui.js';
const fields=['enabled','myProfile','pollMinutes','tokensPerRun','kolMinutes','telegramEnabled','telegramChatId','alertPositionChanges','alertKolChanges'];let loaded=false;let latest=null;let rulesLoaded=false;
async function render(){const r=await send('GET'),s=r.state,c=r.config;latest=r;if(!loaded){for(const k of fields){if($(k).type==='checkbox')$(k).checked=c[k];else $(k).value=c[k];}$('telegramBotToken').placeholder=c.telegramBotToken?'已保存；留空保留':'123456:ABC…';loaded=true;}
 $('status').textContent=`${c.enabled?'后台监控已开启':'后台监控已暂停'} · ${s.status}`;$('auth').textContent=r.auth?`会话：@${r.auth.owner.handle} · ${time(r.auth.at)}${r.auth.owner.manuallyAsserted?' · 所有者由手动确认':''}`:'尚无会话，请手动刷新已登录的 FOMO 页面';$('logs').textContent=s.logs.slice(-100).reverse().map(l=>`${time(l.at)} ${l.level} ${l.message} ${l.path??l.token??''} ${l.http??''} ${l.ms!=null?l.ms+'ms':''}`).join('\n');if(!rulesLoaded){renderRules(r);rulesLoaded=true;}updateCadence();return r;}
async function saveConfig(){const c={activityEnabled:false};for(const k of fields)c[k]=$(k).type==='checkbox'?$(k).checked:$(k).value;c.telegramBotToken=$('telegramBotToken').value;c.clearBot=$('clearBot').checked;await send('SAVE',{config:c});$('telegramBotToken').value='';$('clearBot').checked=false;}
$('save').onclick=()=>action($('save'),async()=>{await saveConfig();await render();});$('refresh').onclick=()=>action($('refresh'),async()=>{rulesLoaded=false;await render();});$('poll').onclick=()=>action($('poll'),async()=>{await send('POLL');await render();});$('testTg').onclick=()=>action($('testTg'),async()=>{await saveConfig();await send('TEST_TG');});$('clearAuth').onclick=()=>action($('clearAuth'),async()=>{await send('CLEAR_AUTH');await render();});$('manualAuth').onclick=()=>action($('manualAuth'),async()=>{if(!$('ownerConfirmed').checked)throw new Error('请先确认令牌属于当前 Profile');await saveConfig();await send('MANUAL_AUTH',{token:$('manualToken').value});$('manualToken').value='';await render();});$('reset').onclick=()=>action($('reset'),async()=>{if(!confirm(translate('重建基线会清空本插件快照、变化记录和待发送队列；下一次不发送历史变化。继续？')))return;await send('RESET');await render();});$('export').onclick=()=>action($('export'),async()=>{const r=await send('GET');const payload={version:'0.1.0',exportedAt:new Date().toISOString(),state:r.state,settings:{myProfile:r.config.myProfile,pollMinutes:r.config.pollMinutes,tokensPerRun:r.config.tokensPerRun},auth:{present:!!r.auth,owner:r.auth?.owner,at:r.auth?.at}};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download='fomo-monitor-debug.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});render().catch(e=>$('message').textContent=e.message);

$('float').onclick=()=>action($('float'),async()=>{await send('FLOAT');window.close();});
const presets={balanced:[1,5,3],fast:[.5,2,5],eco:[3,15,2]};
function updateCadence(){const n=latest?.state.own?.positions.length??0;const p=Number($('pollMinutes').value)||1;const k=Number($('kolMinutes').value)||5;const b=Number($('tokensPerRun').value)||3;$('cadence').textContent=`全部 ${n} 个持仓：市值约每 ${p<1?'30 秒':p+' 分钟'}检查；KOL 一次完整复查保守估算约 ${k+Math.max(0,Math.ceil(n/b)-1)*p} 分钟（网络耗时另计）。`;const match=Object.entries(presets).find(([,v])=>v[0]===p&&v[1]===k&&v[2]===b);$('preset').value=match?.[0]??'custom';}
$('preset').onchange=()=>{const v=presets[$('preset').value];if(v){['pollMinutes','kolMinutes','tokensPerRun'].forEach((k,i)=>$(k).value=v[i]);updateCadence();}};
for(const k of ['pollMinutes','kolMinutes','tokensPerRun'])$(k).oninput=updateCadence;
const inputCap=n=>Number.isFinite(n)?n>=1e9?n/1e9+'B':n>=1e6?n/1e6+'M':n>=1e3?n/1e3+'K':String(n):'';
function renderRules(r){
 const root=$('rules');root.replaceChildren();const positions=r.state.own?.positions??[];const keys=new Set([...positions.map(p=>p.key),...Object.keys(r.config.marketRules??{})]);
 const toolbar=el('div');for(const [text,value] of [['一键全选告警',true],['全部取消告警',false]]){const b=el('button',text);b.onclick=()=>action(b,async()=>{await send('TOKEN_ALERTS',{all:true,enabled:value});rulesLoaded=false;await render();});toolbar.append(b);}root.append(toolbar);
 for(const key of keys){const p=positions.find(p=>p.key===key),rule=r.config.marketRules?.[key];const card=el('details',null,'rule-card');card.append(el('summary',p?.symbol??key,'notranslate'));
 const content=el('div',null,'token-body');card.append(content);root.append(card);
 const master=el('input');master.type='checkbox';master.checked=tokenAlertsEnabled(r.config,key);const ml=el('label','全部告警（勾选自动保存）');ml.prepend(master);content.append(ml);master.onchange=()=>action(master,async()=>{try{await send('TOKEN_ALERTS',{key,enabled:master.checked});}catch(e){master.checked=!master.checked;throw e;}});
 const enabled=el('input');enabled.type='checkbox';enabled.checked=rule?.enabled??false;const en=el('label','启用市值阈值规则（需保存）');en.prepend(enabled);content.append(en);
 const base=el('input');base.value=inputCap(rule?.base??p?.entryMarketCap);base.placeholder='例如 750K、1.2M';const bl=el('label','基准建仓市值（美元 · 估算）');bl.append(base);content.append(bl);const hint=el('p',null,'muted');content.append(hint);const update=()=>hint.textContent='基准 '+compact(parseCompact(base.value))+' · 平均买入价 × 当前隐含供应量';base.oninput=update;update();
 const use=el('button','使用持仓买入市值');use.disabled=!p?.entryMarketCap;use.onclick=()=>{base.value=inputCap(p.entryMarketCap);update();};content.append(use);if(!p?.entryMarketCap)content.append(el('small','缺少有效买入价时需手动设置，不以当前市值代替。','warn'));
 const editors=[];const initial=rule?.tiers??rule?.multiples?.flatMap(v=>(rule.direction==='both'?['up','down']:[rule.direction??'up']).map(direction=>({direction,mode:'multiple',value:v})))??[{direction:'up',mode:'percent',value:100},{direction:'down',mode:'percent',value:20}];
 for(const direction of ['up','down']){content.append(el('h3',direction==='up'?'📈 上涨提醒':'📉 下跌提醒'));const list=el('div');content.append(list);
 const add=t=>{const row=el('div',null,'rule-row');const mode=el('select');for(const [v,label] of [['percent',direction==='up'?'上涨幅度 %':'下跌幅度 %'],['multiple','基准倍数 ×'],['cap','目标市值 USD']]){const o=el('option',label);o.value=v;mode.append(o);}mode.value=t.mode;const input=el('input');input.value=t.value;input.setAttribute('aria-label',direction==='up'?'上涨阈值':'下跌阈值');const remove=el('button','删除');const item={row,mode,input,direction};editors.push(item);remove.onclick=()=>{editors.splice(editors.indexOf(item),1);row.remove();};row.append(mode,input,remove);list.append(row);};
 initial.filter(t=>t.direction===direction).forEach(add);const button=el('button','＋ 增加'+(direction==='up'?'上涨':'下跌')+'档位');button.onclick=()=>add({mode:'percent',value:direction==='up'?100:20});content.append(button);}
 const preview=el('p',null,'muted');content.append(preview);const getRule=()=>({enabled:enabled.checked,base:base.value,tiers:editors.map(x=>({direction:x.direction,mode:x.mode.value,value:x.input.value}))});
 const check=el('button','预览目标');check.onclick=()=>{try{const v=normalizeRule(getRule());preview.textContent=v.tiers.map(t=>(t.direction==='up'?'上涨至 ':'下跌至 ')+compact(t.target)).join(' / ');}catch(e){preview.textContent=e.message;}};content.append(check);
 for(const [label,rearm] of [['保存该 Token',false],['重新布防',true]]){const b=el('button',label);b.onclick=()=>action(b,async()=>{await send('SAVE_RULE',{key,rule:getRule(),rearm});preview.textContent='已保存 · 等待后续越线';});content.append(b);}
 content.append(el('p','规则仅发送 Telegram 提醒，不自动买卖。每档每方向一次。','muted'));
 }
}
support();
